### ISSUE TITLE
How to calculate the Toeplitz matrix C?

### ISSUE THREAD

**Issue by 16mkor** [lsj2408/URPE#1]
In your paper, you state that you will provide the code. Could you please provide insights about how to implement your URPE approach?

Thank you in advance!

**Comment by dhar174** [comment]
I too, would be very appreciative to see the implementation of the URPE attention function. Can you provide a code or pseudocode example of how to calculate the Toeplitz matrix, and the order of operations you used, etc.

**Comment by lsj2408** [comment]
Sorry for the late reply! The URPE codebase has been updated. To see how the matrix C is calculated, please refer to 
 https://github.com/lsj2408/URPE/blob/47b711f85be5de010deeafa9d8788d399912c3a2/fairseq/modules/transformer_sentence_encoder.py#L259 Feel free to ask for further help~
